name: @module_name@ CI

# Only on Development we build snapshots
on:
  push:
    branches:
      - development
      - master

env:
  MODULE_ID: @MODULE_SLUG@

jobs:
  #############################################
  # Build Module
  #############################################
  build:
    name: Build & Publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_API_TOKEN }}

      - name: Install Build Dependencies
        run: |
          box install

      - name: Setup Environment For Build Process
        id: current_version
        run: |
          # Get latest version from box.json
          echo "VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV
          box package set version=@build.version@+@build.number@
          # master or snapshot
          echo "Github Ref is $GITHUB_REF"
          echo "BRANCH=master" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/development' ]
          then
            echo "BRANCH=development" >> $GITHUB_ENV
          fi

      - name: Build ${{ env.MODULE_ID }}
        run: |
          # Create the CommandBox modules folder, for some reason it is not created
          mkdir -p ~/.CommandBox/cfml/modules
          # Build Project with Tests Included
          box task run taskfile=build/Build :version=${{ env.VERSION }} :projectName=${{ env.MODULE_ID }} :buildID=${{ github.run_number }} :branch=${{ env.BRANCH }}

      - name: Failure Logs
        if: failure()
        run: cat `box system-log`

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: Module Artifacts
          path: |
            .artifacts/**/*

      - name: Upload Binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "downloads.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".artifacts/${{ env.MODULE_ID }}"
          DEST_DIR: "ortussolutions/commandbox-modules/${{ env.MODULE_ID }}"

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/apidocs"
          DEST_DIR: "commandbox-modules/${{ env.MODULE_ID }}/${{ env.VERSION }}"

      - name: Publish To ForgeBox
        run: |
          cd .tmp/${{ env.MODULE_ID }}
          cat box.json
          box forgebox publish

      - name: Inform Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: coding
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON_EMOJI: ":bell:"
          SLACK_MESSAGE: '${{ env.MODULE_ID }} Built with ${{ job.status }}!'
          SLACK_TITLE: "${{ env.MODULE_ID }} Build"
          SLACK_USERNAME: CI
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
