name: Build Snapshot

on:
  push:
    branches:
      - 'development'

jobs:
  ##########################################################################################
  # Module Tests
  ##########################################################################################
  tests:
    secrets: inherit
    uses: ./.github/workflows/tests.yml

  ##########################################################################################
  # Format Source Code
  ##########################################################################################
  format:
    name: Code Auto-Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-format
        uses: Ortus-Solutions/commandbox-action@v1.0.3
        with:
          cmd: run-script format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Apply cfformat changes

  ##########################################################################################
  # Release it
  ##########################################################################################
  release:
    uses: ./.github/workflows/release.yml
    needs: [ tests, format ]
    secrets: inherit
    with:
      snapshot: true
